#!/usr/bin/bash


greet(){
  # option 1 - concise and quick to write
  #local name=${1:-"there"}

  # option 2 - more easily understood by people who don't know bash
  #local name="there"
  #if  test -n "$1" && test -n "$2" ; then
  # Could do if (($# == 2)). However, passing greet '' '' will be true
  # because we are passing through two empty characters which will be
  # counted.

  # option 3 - short circuit logic
  # test -z "$1" && test -z "$2" && echo "usage: greet first [second]" && return 1

  # long form
  if [[ -z "$1$2" || $# -gt 2 ]]; then
    echo "usage: greet first [second]"
    return 1
  fi

  if [[ -n "$1" && -n "$2" ]]; then
    name="$1 $2"
  elif test -n "$1" ; then 
   name=$1
  else
    name=there
  fi

  if [[ "${name,,}" =~ ^yongle ]]; then
    name=${name^^}
  fi

  printf "Hello, %s. \n" "$name"
}

greet "$@"

what()
{
  local what="Mr Yongle"
  printf "%s \n" "$what"
  # Exclude everything up until the first space. Remove the "Mr" part
  printf '%s \n' "${what#* }"
  what="The Honorable Mr Yongle"
  # Excludes everything up until the last space. Remove the "The Honorable Mr "
  printf '%s \n' "${what##* }"
  # Reverse is true if I use ${what% *}. This should print out "Yongle"
  printf '%s \n' "${what% *}"
  # Using ${what/Mr/Doctor} will replace the first instance of Mr
  printf '%s \n' "${what/Mr/Doctor}"
  # Using ${what//o/0} will replace all instances of o with 0
  printf '%s \n' "${what//o/0}"
}

#what






